---
title: "Seeking Help"
format: html
editor: visual
---

The exercises in this document follow along closely with [Lesson 3](https://swcarpentry.github.io/r-novice-gapminder/03-seeking-help.html) of [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/), provided by the [Software Carpentry](https://software-carpentry.org/) community under the creative commons license, [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/). For more information see [The Carpentries](https://carpentries.org/).

### [Seeking Help](https://swcarpentry.github.io/r-novice-gapminder/03-seeking-help/index.html)

::: callout-tip
## Key Points

Use `help()` or `?` to get help in R.
:::

#### Challenge 1

Look at the help page for `c`. What kind of vector do you expect will be created if you evaluate the following?

```{r}
c(1, 2, 3)
c('d', 'e', 'f')
c(1, 2, 'f')
```

<!-- Challenge 1 answer begin -->

c(1, 2, 3) will create a numeric vector containing three numeric values.

c('d', 'e', 'f') will create a character vector containing three character values.

c(1, 2, 'f') will create a character vector because R coerces all elements to the most flexible data type when different types are combined, in this case, character.

<!-- Challenge 1 answer end -->

#### Challenge 2

Look at the help for the `paste` function. You will need to use it later. What's the difference between the `sep` and `collapse` arguments?

<!-- Challenge 2 answer begin -->

sep is an argument in the paste function that specifies the character string to separate the input vectors. It determines what separates the elements when you paste them together. For example, paste("a", "b", sep = "-") will result in "a-b".

collapse is an argument in the paste function that specifies the character string to concatenate the input vectors. It determines what is used to concatenate all the elements into a single string. For example, paste(c("a", "b", "c"), collapse = "-") will result in "a-b-c".

In summary, sep is used to separate elements within a vector, while collapse is used to concatenate elements into a single string.

<!-- Challenge 2 answer end -->

#### Challenge 3

Use help to find a function (and its associated parameters) that you could use to load data from a tabular file in which columns are delimited with "\t\" (tab) and the decimal point is a"." (period). This check for decimal separator is important, especially if you are working with international colleagues, because different countries have different conventions for the decimal point (i.e. comma vs period).

::: {.callout-note collapse="true"}
# Hint

Use `??"read table"` to look up functions related to reading in tabular data.
:::

<!-- Challenge 3 answer begin -->

data \<- read.table("file.txt", sep = "\\t", dec = ".")

<!-- Challenge 3 answer end -->
